"""
test_risk_scoring_and_recommendations.py
=========================================
Comprehensive automated tests verifying:
1. Risk score classification thresholds:
   - 20 -> Low
   - 45 -> Moderate
   - 65 -> High
   - 85 -> Critical -> IDRC recommendation workflow
2. Every model prediction item receives a valid risk score (0-100) and risk level.
3. Consensus items carry risk scores and levels.
4. Screening engine outputs 0-100 scale score and classifies emergency vitals as Critical.
5. Capability-aware hospital recommendation logic prioritizes ICU/emergency facilities
   for critical cases over closer unequipped facilities.
6. API endpoint integration (/api/ml/predict, /api/hospitals/recommend, /api/hospitals/search, /api/assess).
"""

import os
import sys
import pytest

# Ensure backend root is on sys.path
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if BASE_DIR not in sys.path:
    sys.path.insert(0, BASE_DIR)

from fastapi.testclient import TestClient
from main import app
from risk_scoring import (
    classify_risk_level,
    calculate_item_risk,
    get_condition_profile,
    RISK_THRESHOLDS
)
from hospital_recommender import recommend_hospitals
from ml.predictor import disease_predictor
from ml.consensus_engine import consensus_engine
from ml_engine import screening_engine


client = TestClient(app)


# ─── 1. THRESHOLD TESTS (Requirement 2 & 10) ──────────────────────────────────

def test_risk_level_threshold_boundaries():
    """
    Test exact required values:
      - 20 -> Low
      - 45 -> Moderate
      - 65 -> High
      - 85 -> Critical
    Along with boundary conditions (0, 30, 31, 50, 51, 70, 71, 100).
    """
    # Required test values from specification
    assert classify_risk_level(20) == "LOW"
    assert classify_risk_level(45) == "MODERATE"
    assert classify_risk_level(65) == "HIGH"
    assert classify_risk_level(85) == "CRITICAL"

    # Boundary conditions
    assert classify_risk_level(0) == "LOW"
    assert classify_risk_level(30) == "LOW"
    assert classify_risk_level(31) == "MODERATE"
    assert classify_risk_level(50) == "MODERATE"
    assert classify_risk_level(51) == "HIGH"
    assert classify_risk_level(70) == "HIGH"
    assert classify_risk_level(71) == "CRITICAL"
    assert classify_risk_level(100) == "CRITICAL"


def test_centralized_thresholds_configuration():
    """Verify thresholds dictionary is centralized and structured properly."""
    assert "LOW" in RISK_THRESHOLDS
    assert "MODERATE" in RISK_THRESHOLDS
    assert "HIGH" in RISK_THRESHOLDS
    assert "CRITICAL" in RISK_THRESHOLDS
    assert RISK_THRESHOLDS["LOW"] == (0, 30)
    assert RISK_THRESHOLDS["MODERATE"] == (31, 50)
    assert RISK_THRESHOLDS["HIGH"] == (51, 70)
    assert RISK_THRESHOLDS["CRITICAL"] == (71, 100)


# ─── 2. PREDICTION ITEM SCORING TESTS (Requirement 1 & 10) ────────────────────

def test_every_predicted_item_receives_risk_score():
    """
    Verify that every item generated by DiseasePredictor has:
    - risk_score between 0 and 100
    - valid risk_level (LOW, MODERATE, HIGH, CRITICAL)
    - item_id and required_specialty
    """
    result = disease_predictor.predict_disease(["fever", "cough", "fatigue"])
    predictions = result.get("predictions", [])
    assert len(predictions) > 0

    for item in predictions:
        assert "risk_score" in item
        assert "risk_level" in item
        assert "item_id" in item
        assert "required_specialty" in item
        
        # Verify score is in valid [0, 100] range
        assert 0.0 <= item["risk_score"] <= 100.0
        assert item["risk_level"] in ["LOW", "MODERATE", "HIGH", "CRITICAL"]
        assert len(item["item_id"]) > 0
        assert len(item["required_specialty"]) > 0


def test_item_risk_deterministic_and_condition_aware():
    """
    Verify that calculate_item_risk scores acute conditions higher than mild ones.
    """
    # Emergency condition vs benign condition
    cardiac_risk = calculate_item_risk(0.8, "angina", ["chest pain"])
    skin_risk = calculate_item_risk(0.8, "acne", [])

    assert cardiac_risk["risk_score"] > skin_risk["risk_score"]
    assert cardiac_risk["risk_level"] in ["HIGH", "CRITICAL"]
    assert skin_risk["risk_level"] == "LOW"


def test_consensus_engine_items_have_risk_scores():
    """Verify hybrid consensus predictions carry risk scores and levels."""
    result = consensus_engine.predict(["chest pain", "dizziness"])
    consensus_preds = result.get("predictions", [])
    assert len(consensus_preds) > 0

    for item in consensus_preds:
        assert "risk_score" in item
        assert "risk_level" in item
        assert 0.0 <= item["risk_score"] <= 100.0
        assert item["risk_level"] in ["LOW", "MODERATE", "HIGH", "CRITICAL"]


# ─── 3. SCREENING ENGINE EVALUATION TESTS ─────────────────────────────────────

def test_screening_engine_low_risk_baseline():
    """Test standard normal vitals yield Low risk on 0-100 scale."""
    eval_res = screening_engine.evaluate({
        "symptoms": ["mild fatigue"],
        "systolic_bp": 118,
        "diastolic_bp": 78,
        "glucose_mg_dl": 95,
        "temperature_f": 98.6
    })
    assert 0.0 <= eval_res["risk_score"] <= 30.0
    assert eval_res["risk_level"] == "LOW"


def test_screening_engine_critical_emergency_vitals():
    """Test hypertensive crisis vitals trigger score > 70 and CRITICAL."""
    eval_res = screening_engine.evaluate({
        "symptoms": ["chest pain", "shortness of breath"],
        "systolic_bp": 195,
        "diastolic_bp": 125,
        "glucose_mg_dl": 140,
        "temperature_f": 99.0
    })
    assert eval_res["risk_score"] > 70.0
    assert eval_res["risk_level"] == "CRITICAL"
    assert "CRITICAL EMERGENCY ALERT" in eval_res["recommended_action"]


# ─── 4. CAPABILITY-AWARE HOSPITAL RECOMMENDATION TESTS (Requirements 5 & 6) ───

def test_hospital_recommendation_critical_prioritizes_capability_over_distance():
    """
    CRITICAL REQUIREMENT TEST:
    For a Critical case (e.g. angina, risk_score=85):
    - Top hospital must have 24/7 Emergency and ICU capability
    - Recommendation priority must be CRITICAL
    - Must NOT simply pick the closest facility (e.g. Sundarpur PHC is 1.1 km away
      but has no ICU/Emergency, so District Trauma Hospital at 4.8 km must rank higher).
    """
    recs = recommend_hospitals(
        condition="angina",
        risk_score=85.0,
        user_lat=22.723,
        user_lng=88.483,
        max_results=5
    )
    assert len(recs) > 0
    top_hospital = recs[0]

    # Top recommendation MUST have 24/7 Emergency and ICU for Critical cardiac case
    assert top_hospital["is_emergency_24x7"] is True
    assert top_hospital["icu_beds_available"] > 0
    assert top_hospital["recommendation_priority"] == "CRITICAL"
    assert "Emergency Priority Match" in top_hospital["reason"]
    assert top_hospital["travel_time_min"] > 0
    assert len(top_hospital["capability_match"]) > 0


def test_hospital_recommendation_routine_moderate_case():
    """
    For a moderate case (risk_score=45), routine community facilities are valid.
    """
    recs = recommend_hospitals(
        condition="anemia",
        risk_score=45.0,
        user_lat=22.723,
        user_lng=88.483,
        max_results=5
    )
    assert len(recs) > 0
    # No emergency panic priority
    assert any(h["recommendation_priority"] in ["HIGH", "STANDARD"] for h in recs)


# ─── 5. FULL API FLOW INTEGRATION TESTS (Requirement 7) ───────────────────────

def test_api_ml_predict_endpoint_response_structure():
    """Verify /api/ml/predict includes risk_score and risk_level for every item."""
    response = client.post("/api/ml/predict", json={"symptoms": ["fever", "cough"]})
    assert response.status_code == 200
    data = response.json()
    predictions = data.get("predictions", [])
    assert len(predictions) > 0

    for p in predictions:
        assert "risk_score" in p
        assert "risk_level" in p
        assert "item_id" in p
        assert 0.0 <= p["risk_score"] <= 100.0
        assert p["risk_level"] in ["LOW", "MODERATE", "HIGH", "CRITICAL"]


def test_api_hospital_recommend_post_critical_workflow():
    """
    Verify POST /api/hospitals/recommend for Critical case (score=85):
    - Banner displays 'Risk Score: 85/100 — Critical'
    - is_critical is True
    - Recommendations returned with required fields
    """
    payload = {
        "item_id": "item_angina_85",
        "condition": "angina",
        "risk_score": 85.0,
        "specialty": "Cardiology"
    }
    response = client.post("/api/hospitals/recommend", json=payload)
    assert response.status_code == 200
    data = response.json()

    assert data["patient_risk_score"] == 85.0
    assert data["patient_risk_level"] == "CRITICAL"
    assert data["is_critical"] is True
    assert "Risk Score: 85/100 — Critical" in data["recommendation_banner"]
    
    hospitals = data.get("hospitals", [])
    assert len(hospitals) > 0
    assert hospitals[0]["is_emergency_24x7"] is True
    assert "distance" in hospitals[0]
    assert "travel_time" in hospitals[0]
    assert "specialty_match" in hospitals[0]
    assert "reason" in hospitals[0]


def test_api_hospital_recommend_get_endpoint():
    """Verify GET /api/hospitals/recommend with query parameters."""
    response = client.get("/api/hospitals/recommend?condition=diabetes&risk_score=45.0")
    assert response.status_code == 200
    data = response.json()
    assert data["patient_risk_score"] == 45.0
    assert data["patient_risk_level"] == "MODERATE"
    assert "Risk Score: 45/100 — Moderate" in data["recommendation_banner"]
    assert len(data["hospitals"]) > 0


def test_api_hospital_search_backward_compatibility():
    """Verify /api/hospitals/search continues working with enhanced capability fields."""
    response = client.get("/api/hospitals/search?location=Barasat")
    assert response.status_code == 200
    data = response.json()
    assert "hospitals" in data
    assert "center" in data
    hospitals = data["hospitals"]
    assert len(hospitals) > 0
    assert "suitability_score" in hospitals[0]
    assert "travel_time" in hospitals[0]
    assert "reason" in hospitals[0]


def test_api_assessment_creation_and_risk_persistence():
    """
    Verify complete flow:
    Client sends vitals -> assessment created in DB -> 0-100 score and level saved and returned.
    """
    # 1. Create patient
    p_resp = client.post("/api/patients", json={
        "name": "Sunita Devi",
        "age": 48,
        "gender": "Female",
        "village": "Sundarpur",
        "phone": "9876543210"
    })
    assert p_resp.status_code == 200
    patient_id = p_resp.json()["id"]

    # 2. Submit assessment with critical vitals
    ass_resp = client.post("/api/assess", json={
        "patient_id": patient_id,
        "symptoms": ["chest pain", "shortness of breath"],
        "systolic_bp": 185,
        "diastolic_bp": 120,
        "glucose_mg_dl": 210,
        "temperature_f": 99.2
    })
    assert ass_resp.status_code == 200
    ass_data = ass_resp.json()

    assert ass_data["risk_score"] > 70.0
    assert ass_data["risk_level"] == "CRITICAL"
    assert ass_data["referral_status"] in ["REFERRED", "NOT_REFERRED"]

    # 3. Retrieve assessments list and verify score was persisted
    list_resp = client.get("/api/assessments")
    assert list_resp.status_code == 200
    saved_list = list_resp.json()
    matching = [a for a in saved_list if a["id"] == ass_data["id"]]
    assert len(matching) == 1
    assert matching[0]["risk_score"] == ass_data["risk_score"]
    assert matching[0]["risk_level"] == "CRITICAL"
